<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Bitbound.SystemAbstractions</RootNamespace>
    <AssemblyName>Bitbound.SystemAbstractions</AssemblyName>
    <Description>Operating system abstractions (file system, processes, environment, and Windows registry) for improved service testability.</Description>
    <PackageTags>os;operating-system;abstractions;file-system;process;processes;registry;environment;di;testability</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
